### ISSUE TITLE
Country Code field error

### ISSUE THREAD

**Issue by yashchaudhari008** [yashchaudhari008/unsaved-contact-to-whatsapp-chat#4]
The country code field can take any text as input and also with whitespace.

Country Code should only take numbers and '+' symbol

Screenshot:-
![image](https://user-images.githubusercontent.com/29065088/197403695-04acadae-a7f4-4a4f-9362-53a735301f68.png)

**Comment by vijay1155** [comment]
Assign me

**Comment by V3ntus** [comment]
Just set the filter in the HTML input tag

**Comment by Brujitari** [comment]
I tried this and did a PR in case it's useful
